<?php
require_once './vendor/autoload.php';
use tekki\core\html\HTML;
use tekki\core\w3css\W3css as W3;
$html = new HTML();
$html->setLang('de');
$head = $html->head();
$head->meta()->charset();
$head->meta()->viewport();
$head->meta()->author('Authorname');
$head->meta()->applicationName('Applicationname');
$head->meta()->description('This Application is for showing Texts or Images in a HTML-Format.');
$head->meta()->keywords('Composer PHP HTML5 Bibliothek');
$head->includeCSS('W3.css');
$head->includeCSS('demo.css');
$body = $html->body();
$body->setClass(W3::BLACK);
$header = $body->header();
$header->setClass(W3::BLUE_GREY);
$h1 = $header->h1();
$h1->setClass(W3::TEXT_DEEP_ORANGE.W3::HOVER_AMBER);
$h1->text('Composer PHP HTML5 Bibliothek');
$div = $body->div();
$nav = $div->nav();
$nav->setClass(W3::LIGHT_BLUE);
$ul = $nav->ul();
$button = $ul->li()->button();
$button->onClick('alert(\'home\');');
$main = $div->main();
$main->setClass(W3::LIGHT_GREY);
$main->text('Content');
$footer = $body->footer();
$footer->setClass(W3::BLUE_GREY);
$footer->text('Footer');
$img = $body->img();
$img->setSrc('pic/ohne_gentechnik.jpg');
$img->setClass('fu');
$input = $body->input();
// $img->attrWidth('100px');
// $img->attrHeight('100px');
// $img->attrAlt('Bioland');
/*
    GlobalAttributes
    use Accesskey;
    use _Class;
    use Contenteditable;
    use DataCustom;
    use Dir;
    use Draggable;
    use Hidden;
    use Lang;
    use Spellcheck;
    use Style;
    use Tabindex;
    use Title;
    use Translate;
*/